# 31261 Internetworking Project

In [ ]:
!pip install kagglehub

In [ ]:
import kagglehub
path = kagglehub.dataset_download("chethuhn/network-intrusion-dataset")
print("Dataset:", path)

In [ ]:
import pandas as pd
import os
path = "/kaggle/input/datasets/chethuhn/network-intrusion-dataset"
os.listdir(path)

In [ ]:
files = os.listdir(path)
dfs = []

for file in files:
  if file.endswith(".csv"):
    df = pd.read_csv(f"{path}/{file}")
    dfs.append(df)

data = pd.concat(dfs, ignore_index=True)

In [ ]:
data.head(10)

In [11]:
#data.isna().sum()

 Destination Port              0
 Flow Duration                 0
 Total Fwd Packets             0
 Total Backward Packets        0
Total Length of Fwd Packets    0
                              ..
Idle Mean                      0
 Idle Std                      0
 Idle Max                      0
 Idle Min                      0
 Label                         0
Length: 79, dtype: int64

In [12]:
#data.isnull().sum()

 Destination Port              0
 Flow Duration                 0
 Total Fwd Packets             0
 Total Backward Packets        0
Total Length of Fwd Packets    0
                              ..
Idle Mean                      0
 Idle Std                      0
 Idle Max                      0
 Idle Min                      0
 Label                         0
Length: 79, dtype: int64

In [ ]:
data.columns

In [ ]:
data.drop(columns=[' Packet Length Variance', ' Fwd Header Length.1', ' Bwd PSH Flags', 'Fwd PSH Flags',
                   ' Fwd URG Flags',' Bwd URG Flags','FIN Flag Count',' SYN Flag Count',
                   ' RST Flag Count',' PSH Flag Count',' ACK Flag Count',' URG Flag Count',
                   ' CWE Flag Count',' ECE Flag Count','Fwd Avg Bytes/Bulk',' Fwd Avg Packets/Bulk',
                   ' Fwd Avg Bulk Rate',' Bwd Avg Bytes/Bulk',' Bwd Avg Packets/Bulk','Bwd Avg Bulk Rate',
                   'Subflow Fwd Packets',' Subflow Fwd Bytes',' Subflow Bwd Packets',' Subflow Bwd Bytes',
                   'Init_Win_bytes_forward',' Init_Win_bytes_backward',' act_data_pkt_fwd',' min_seg_size_forward',
                   ' Active Std',' Active Max',' Active Min',' Idle Std',' Idle Max',' Idle Min', ' Fwd IAT Min',
                   'Bwd IAT Total', ' Bwd IAT Mean', ' Bwd IAT Std',
                   ' Bwd IAT Max', ' Bwd IAT Min', ' Fwd Header Length',
                   ' Bwd Header Length', ' Down/Up Ratio', ' Avg Fwd Segment Size',
                   ' Avg Bwd Segment Size', 'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std', ' Fwd IAT Max', 'Bwd Packet Length Max',
                   ' Bwd Packet Length Min', ' Fwd Packet Length Max', ' Fwd Packet Length Min', ' Min Packet Length',
                   ' Max Packet Length', 'Active Mean', 'Idle Mean', ' Destination Port', ' Fwd Packet Length Std',  ' Bwd Packet Length Std',
                   'Fwd Packets/s', ' Bwd Packets/s'], inplace=True)

In [ ]:
data.columns

In [ ]:
data

In [ ]:
data.dtypes

In [106]:
#data = data.astype({' Label':'category'})
#data.dtypes

 Destination Port                 int64
 Flow Duration                    int64
 Total Fwd Packets                int64
 Total Backward Packets           int64
Total Length of Fwd Packets       int64
                                 ...
Idle Mean                       float64
 Idle Std                       float64
 Idle Max                         int64
 Idle Min                         int64
 Label                         category
Length: 79, dtype: object

In [ ]:
data.columns = data.columns.str.strip()
#data.columns

In [20]:
#pd.options.display.float_format = '{:.2f}'.format

In [66]:
#data

,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Mean,Bwd Packet Length Mean,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Packet Length Mean,Packet Length Std,Average Packet Size,Label
0,1266342,41,44,2664,6954,64.98,158.05,7595.10,67.12,15075.50,104051.40,948537,0,111.84,239.69,113.15,Malicious
1,1319353,41,44,2664,6954,64.98,158.05,7289.94,64.43,15706.58,104861.87,955790,1,111.84,239.69,113.15,Malicious
2,160,1,1,0,0,0.00,0.00,0.00,12500.00,160.00,0.00,160,160,0.00,0.00,0.00,Malicious
3,1303488,41,42,2728,6634,66.54,157.95,7182.27,63.68,15896.20,106554.90,956551,0,111.45,241.64,112.80,Malicious
4,77,1,2,0,0,0.00,0.00,0.00,38961.04,38.50,14.85,49,28,0.00,0.00,0.00,Malicious
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2830735,46982,2,2,58,446,29.00,223.00,10727.51,85.14,15660.67,27120.74,46977,1,106.60,106.26,133.25,Malicious
2830736,11512230,5,5,672,3525,134.40,705.00,364.57,0.87,1279136.67,2565059.83,6506213,4,381.55,725.32,419.70,Malicious
2830738,32215,4,2,112,152,28.00,76.00,8194.94,186.25,6443.00,13617.58,30780,3,41.71,23.42,48.67,Malicious
2830741,1048635,6,2,192,256,32.00,128.00,427.22,7.63,149805.00,375521.04,1000947,1,53.33,42.33,60.00,Malicious
2830742,94939,4,2,188,226,47.00,113.00,4360.69,63.20,18987.80,31664.10,73049,1,65.86,32.20,76.83,Malicious

### pd.options.display.float_format = '{:.4f}'.format
data[data.duplicated()]

In [ ]:
data.drop_duplicates(inplace=True)

In [24]:
#data

,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Mean,Bwd Packet Length Mean,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Packet Length Mean,Packet Length Std,Average Packet Size,Label
0,1266342,41,44,2664,6954,64.9756,158.0455,7595.1046,67.1225,15075.5000,104051.3997,948537,0,111.8372,239.6868,113.1529,BENIGN
1,1319353,41,44,2664,6954,64.9756,158.0455,7289.9368,64.4255,15706.5833,104861.8701,955790,1,111.8372,239.6868,113.1529,BENIGN
2,160,1,1,0,0,0.0000,0.0000,0.0000,12500.0000,160.0000,0.0000,160,160,0.0000,0.0000,0.0000,BENIGN
3,1303488,41,42,2728,6634,66.5366,157.9524,7182.2679,63.6753,15896.1951,106554.8990,956551,0,111.4524,241.6428,112.7952,BENIGN
4,77,1,2,0,0,0.0000,0.0000,0.0000,38961.0390,38.5000,14.8492,49,28,0.0000,0.0000,0.0000,BENIGN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2830735,46982,2,2,58,446,29.0000,223.0000,10727.5127,85.1390,15660.6667,27120.7403,46977,1,106.6000,106.2582,133.2500,BENIGN
2830736,11512230,5,5,672,3525,134.4000,705.0000,364.5688,0.8686,1279136.6670,2565059.8350,6506213,4,381.5455,725.3186,419.7000,DoS GoldenEye
2830738,32215,4,2,112,152,28.0000,76.0000,8194.9402,186.2486,6443.0000,13617.5795,30780,3,41.7143,23.4216,48.6667,BENIGN
2830741,1048635,6,2,192,256,32.0000,128.0000,427.2221,7.6290,149805.0000,375521.0405,1000947,1,53.3333,42.3320,60.0000,BENIGN
2830742,94939,4,2,188,226,47.0000,113.0000,4360.6948,63.1985,18987.8000,31664.1026,73049,1,65.8571,32.2047,76.8333,BENIGN

In [ ]:
pd.options.display.float_format = '{:.2f}'.format

In [63]:
#data.head()

,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Mean,Bwd Packet Length Mean,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Packet Length Mean,Packet Length Std,Average Packet Size,Label
0,1266342,41,44,2664,6954,64.98,158.05,7595.10,67.12,15075.50,104051.40,948537,0,111.84,239.69,113.15,Malicious
1,1319353,41,44,2664,6954,64.98,158.05,7289.94,64.43,15706.58,104861.87,955790,1,111.84,239.69,113.15,Malicious
2,160,1,1,0,0,0.00,0.00,0.00,12500.00,160.00,0.00,160,160,0.00,0.00,0.00,Malicious
3,1303488,41,42,2728,6634,66.54,157.95,7182.27,63.68,15896.20,106554.90,956551,0,111.45,241.64,112.80,Malicious
4,77,1,2,0,0,0.00,0.00,0.00,38961.04,38.50,14.85,49,28,0.00,0.00,0.00,Malicious

In [ ]:
data['Label'].value_counts()

In [ ]:
data['Label'] = data['Label'].astype(str).str.strip()
data['Label'] = data['Label'].apply(
    lambda x: 'Benign' if x.upper() == 'BENIGN' else 'Malicious'
)

In [161]:
data['Label'].value_counts()

Label
Benign       1646115
Malicious     335249
Name: count, dtype: int64

In [ ]:
import numpy as np

data.replace([np.inf, -np.inf], np.nan, inplace=True)
data.fillna(0, inplace=True)

In [164]:
data

,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Mean,Bwd Packet Length Mean,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Packet Length Mean,Packet Length Std,Average Packet Size,Label,BinaryLabel
0,1266342,41,44,2664,6954,64.98,158.05,7595.10,67.12,15075.50,104051.40,948537,0,111.84,239.69,113.15,Benign,0
1,1319353,41,44,2664,6954,64.98,158.05,7289.94,64.43,15706.58,104861.87,955790,1,111.84,239.69,113.15,Benign,0
2,160,1,1,0,0,0.00,0.00,0.00,12500.00,160.00,0.00,160,160,0.00,0.00,0.00,Benign,0
3,1303488,41,42,2728,6634,66.54,157.95,7182.27,63.68,15896.20,106554.90,956551,0,111.45,241.64,112.80,Benign,0
4,77,1,2,0,0,0.00,0.00,0.00,38961.04,38.50,14.85,49,28,0.00,0.00,0.00,Benign,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2830735,46982,2,2,58,446,29.00,223.00,10727.51,85.14,15660.67,27120.74,46977,1,106.60,106.26,133.25,Benign,0
2830736,11512230,5,5,672,3525,134.40,705.00,364.57,0.87,1279136.67,2565059.83,6506213,4,381.55,725.32,419.70,Malicious,1
2830738,32215,4,2,112,152,28.00,76.00,8194.94,186.25,6443.00,13617.58,30780,3,41.71,23.42,48.67,Benign,0
2830741,1048635,6,2,192,256,32.00,128.00,427.22,7.63,149805.00,375521.04,1000947,1,53.33,42.33,60.00,Benign,0
2830742,94939,4,2,188,226,47.00,113.00,4360.69,63.20,18987.80,31664.10,73049,1,65.86,32.20,76.83,Benign,0

In [ ]:
data.isnull().values.any()

In [ ]:
data.isna().values.any()

In [ ]:
np.isinf(data.select_dtypes(include=np.number)).sum().sum()

In [ ]:
#Resetting the indexes
data.reset_index(drop=True, inplace=True)

In [ ]:
#coding

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# plot settings
plt.style.use('default')
sns.set_theme()
pd.set_option('display.max_columns', None)

In [ ]:
selected_features = [
    'Packet Length Mean',
    'Packet Length Std',
    'Average Packet Size',
    'Flow Duration',
    'Flow Bytes/s',
    'Flow Packets/s',
    'Flow IAT Mean',
    'Flow IAT Std',
    'Flow IAT Min',
    'Flow IAT Max',
    'Total Fwd Packets',
    'Total Backward Packets',
    'Total Length of Fwd Packets',
    'Total Length of Bwd Packets',
    'Fwd Packet Length Mean',
    'Bwd Packet Length Mean'
]

In [ ]:
print(selected_features)

In [ ]:
missing = [col for col in selected_features if col not in data.columns]
print("Missing columns:", missing)

In [ ]:
data[selected_features].head()

In [ ]:
print("Shape of dataset:", data.shape)
print("\nColumn names:")
print(data.columns.tolist())

print("\nData types:")
print(data.dtypes)

print("\nMissing values in selected features:")
print(data[selected_features + ['Label']].isnull().sum())

In [ ]:
# 1. Shape check
print(data.shape)

# 2. Columns check
print(set(selected_features).issubset(set(data.columns)))

# 3. Missing values check
print(data[selected_features].isnull().sum().sum())

# 4. Label check
print(data['Label'].value_counts())

In [ ]:
data[selected_features + ['Label']].head()

In [ ]:
data[selected_features + ['Label']].head().to_string()

In [ ]:
eda_summary = data[selected_features].describe().T
eda_summary

In [ ]:
eda_summary['median'] = data[selected_features].median()
eda_summary['skewness'] = data[selected_features].skew()
eda_summary['kurtosis'] = data[selected_features].kurtosis()

eda_summary

In [ ]:
label_counts = data['Label'].value_counts()
print(label_counts)

plt.figure(figsize=(6,4))
sns.countplot(x='Label', data=data)
plt.title('Class Distribution of Network Traffic')
plt.xlabel('Traffic Class')
plt.ylabel('Count')
plt.show()

In [ ]:
label_percent = data['Label'].value_counts(normalize=True) * 100
print(label_percent)

In [ ]:
data[selected_features].hist(figsize=(20, 18), bins=30, edgecolor='black')
plt.suptitle('Histograms of Selected Behavioural Features', fontsize=16)
plt.tight_layout()
plt.show()

In [ ]:
print(data.columns.tolist())

In [ ]:
data.columns = data.columns.str.strip()
print(data.columns.tolist())

In [ ]:
missing = [col for col in selected_features if col not in data.columns]
print("Missing columns:", missing)

In [ ]:
sample_data = data[selected_features].sample(n=50000, random_state=42)

sample_data.hist(figsize=(20, 18), bins=30, edgecolor='black')
plt.suptitle('Histograms of Selected Behavioural Features', fontsize=16)
plt.tight_layout()
plt.show()

In [ ]:
import numpy as np

inf_counts = np.isinf(data[selected_features]).sum()
print(inf_counts)

In [ ]:
data[selected_features] = data[selected_features].replace([np.inf, -np.inf], np.nan)

In [ ]:
data[selected_features] = data[selected_features].fillna(0)

In [ ]:
print(np.isinf(data[selected_features]).sum().sum())
print(data[selected_features].isnull().sum().sum())

In [ ]:
sample_data = data[selected_features].sample(n=50000, random_state=42)

sample_data.hist(figsize=(20, 18), bins=30, edgecolor='black')
plt.suptitle('Histograms of Selected Behavioural Features', fontsize=16)
plt.tight_layout()
plt.show()

In [ ]:
plt.figure(figsize=(20, 8))
sns.boxplot(data=data[selected_features], orient='h')
plt.title('Boxplots of Selected Behavioural Features')
plt.xlabel('Feature Value')
plt.show()

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme()

In [ ]:
import numpy as np

log_data = data[selected_features].copy()
log_data = log_data.replace(0, 1e-9)
log_data = np.log10(log_data)

log_data.hist(figsize=(20, 18), bins=30)
plt.show()

In [ ]:
plt.figure(figsize=(7,5))

sns.scatterplot(
    data=data,
    x='Flow Duration',
    y='Flow Bytes/s',
    hue='Label',
    alpha=0.6
)

plt.title('Flow Duration vs Flow Bytes/s')
plt.show()

In [ ]:
plt.figure(figsize=(7,5))

sns.scatterplot(
    data=data,
    x='Flow Packets/s',
    y='Average Packet Size',
    hue='Label',
    alpha=0.6
)

plt.title('Flow Packets/s vs Average Packet Size')
plt.show()

In [ ]:
sample_data = data[selected_features].sample(n=50000, random_state=42)

In [ ]:
corr_matrix = sample_data.corr()
print(corr_matrix.head())

In [ ]:
plt.figure(figsize=(12,8))

sns.heatmap(
    corr_matrix,
    cmap='coolwarm',
    annot=False   # keep False for clean look
)

plt.title('Correlation Heatmap of Selected Features')
plt.show()

## Model Implementation

### Imported Libraries

In [ ]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
from sklearn.model_selection import (train_test_split, GridSearchCV)
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report,
    roc_auc_score,
    roc_curve
)

### Converting the target data labels into binary labels

In [ ]:
data['BinaryLabel'] = data['Label'].astype(str).str.strip().apply(lambda x:0 if x == 'Benign' else 1)

In [ ]:
print(data['BinaryLabel'].value_counts())

In [ ]:
X = data.drop(columns=['Label', 'BinaryLabel'])
y = data['BinaryLabel']

### Splitting the dataset for training and testing

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
x_test_scaled = scaler.transform(X_test)

In [ ]:
print(y_train.value_counts())

### Model 1: Logistic Regression

In [ ]:
m1_params = {
    'C': [0.001, 0.01, 0.1, 1, 10, 100],
    'penalty': ['l1', 'l2'],
    'solver': ['liblinear']
}

m1_grid = GridSearchCV(
    estimator=LogisticRegression(max_iter=1000, class_weight='balanced'),
    param_grid=m1_params,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

m1_grid.fit(X_train_scaled, y_train)
print("Best Parameters for Model 1: ", m1_grid.best_params_)
print("Best CV Score of Model 1: ", m1_grid.best_score_)

m1_lr = m1_grid.best_estimator_
m1_pred = m1_lr.predict(X_test_scaled)
m1_prob = m1_lr.predict_proba(X_test_scaled)[:,1]

In [ ]:
print("Results from M1: Logisitic Regression")
print("Accuracy:", accuracy_score(y_test, m1_pred))
print("Precision:", precision_score(y_test, m1_pred))
print("Recall:", recall_score(y_test, m1_pred))
print("F1-score:", f1_score(y_test, m1_pred))
print("ROC-AUC:", roc_auc_score(y_test, m1_prob))
print("Confusion Matrix:\n", confusion_matrix(y_test, m1_pred))
print(classification_report(y_test, m1_pred))

### Model 2: Random Forest

In [ ]:
m2_params = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

m2_grid = GridSearchCV(
    estimator=RandomForestClassifier(class_weight='balanced', random_state=42),
    param_grid=m2_params,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

m2_grid.fit(X_train, y_train)
print("Best Parameters for Model 2: ", m2_grid.best_params_)
print("Best CV Score of Model 2: ", m2_grid.best_score_)

m2_rf = m2_grid.best_estimator_
m2_pred = m2_rf.predict(X_test)
m2_prob = m2_rf.predict_proba(X_test)[:,1]

In [ ]:
print("Results from M2: Random Forest")
print("Accuracy:", accuracy_score(y_test, m2_pred))
print("Precision:", precision_score(y_test, m2_pred))
print("Recall:", recall_score(y_test, m2_pred))
print("F1-score:", f1_score(y_test, m2_pred))
print("ROC-AUC:", roc_auc_score(y_test, m2_prob))
print("Confusion Matrix:\n", confusion_matrix(y_test, m2_pred))
print(classification_report(y_test, m2_pred))

### Model 3: SVM

In [ ]:
m3_params = {
    'C': [0.1, 1, 10],
    'kernel': ['linear', 'rbf'],
    'gamma': ['scale', 'auto']
}

m3_grid = GridSearchCV(
    estimator=SVC(class_weight='balanced', random_state=42, probability=True),
    param_grid=m3_params,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

m3_grid.fit(X_train_scaled, y_train)
print("Best Parameters for Model 3: ", m3_grid.best_params_)
print("Best CV Score of Model 3: ", m3_grid.best_score_)

m3_svm = m3_grid.best_estimator_
m3_pred = m3_svm.predict(X_test_scaled)
m3_prob = m3_svm.predict_proba(X_test_scaled)[:,1]

In [ ]:
print("Results from M3: Support Vector Machine")
print("Accuracy:", accuracy_score(y_test, m3_pred))
print("Precision:", precision_score(y_test, m3_pred))
print("Recall:", recall_score(y_test, m3_pred))
print("F1-score:", f1_score(y_test, m3_pred))
print("ROC-AUC:", roc_auc_score(y_test, m3_prob))
print("Confusion Matrix:\n", confusion_matrix(y_test, m3_pred))
print(classification_report(y_test, m3_pred))